// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"alkitab/configs"
	"alkitab/controllers"
	"alkitab/entitys"
	"alkitab/services"
	"gorm.io/gorm"
)

// Injectors from injector.go:

func InitializedServer() *Server {
	db := ProvideSQLConnect()
	userService := ProvideUserService(db)
	mailService := ProvideMailService()
	v := ProvideEmailWorker(mailService)
	userController := ProvideUserController(userService, mailService, v)
	server := &Server{
		UserController: userController,
	}
	return server
}

// injector.go:

func ProvideSQLConnect() *gorm.DB {
	db := configs.ConnectPostgre()
	db.AutoMigrate(&entitys.UsersLetstalk{})
	return db
}

func ProvideUserService(db *gorm.DB) *services.UserService {
	return services.NewUserService(db)
}

func ProvideMailService() *services.MailService {
	return services.NewMailService()
}

func ProvideEmailWorker(mailService *services.MailService) chan services.EmailJob {
	return services.StartEmailWorkerPool(mailService, 5)
}

func ProvideUserController(userService *services.UserService, mailService *services.MailService, emailJob chan services.EmailJob) *controllers.UserController {
	ctrl := controllers.NewUserController(userService, mailService)
	ctrl.EmailJobs = emailJob
	return ctrl
}

type Server struct {
	UserController *controllers.UserController
}
